export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_JOB = 'GET_JOB';
export const GET_JOB_REQUEST = 'GET_JOB_REQUEST';
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const GET_JOB_FAILURE = 'GET_JOB_FAILURE';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAILURE = 'UPDATE_JOB_FAILURE';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';

export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_CUSTOMER_REQUEST = 'GET_CUSTOMER_REQUEST';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAILURE = 'GET_CUSTOMER_FAILURE';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE';

export const GET_INVOICE = 'GET_INVOICE';
export const GET_INVOICE_REQUEST = 'GET_INVOICE_REQUEST';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAILURE = 'GET_INVOICE_FAILURE';

export const GET_INVOICES = 'GET_INVOICES';
export const GET_INVOICES_REQUEST = 'GET_INVOICES_REQUEST';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAILURE = 'GET_INVOICES_FAILURE';


export const GET_INVOICEITEM = 'GET_INVOICEITEM';
export const GET_INVOICEITEM_REQUEST = 'GET_INVOICEITEM_REQUEST';
export const GET_INVOICEITEM_SUCCESS = 'GET_INVOICEITEM_SUCCESS';
export const GET_INVOICEITEM_FAILURE = 'GET_INVOICEITEM_FAILURE';

export const GET_INVOICEITEMS = 'GET_INVOICEITEMS';
export const GET_INVOICEITEMS_REQUEST = 'GET_INVOICEITEMS_REQUEST';
export const GET_INVOICEITEMS_SUCCESS = 'GET_INVOICEITEMS_SUCCESS';
export const GET_INVOICEITEMS_FAILURE = 'GET_INVOICEITEMS_FAILURE';


export const GET_TICKETITEM = 'GET_TICKETITEM';
export const GET_TICKETITEM_REQUEST = 'GET_TICKETITEM_REQUEST';
export const GET_TICKETITEM_SUCCESS = 'GET_TICKETITEM_SUCCESS';
export const GET_TICKETITEM_FAILURE = 'GET_TICKETITEM_FAILURE';

export const GET_TICKETITEMS = 'GET_TICKETITEMS';
export const GET_TICKETITEMS_REQUEST = 'GET_TICKETITEMS_REQUEST';
export const GET_TICKETITEMS_SUCCESS = 'GET_TICKETITEMS_SUCCESS';
export const GET_TICKETITEMS_FAILURE = 'GET_TICKETITEMS_FAILURE';


export const GET_ITEM = 'GET_ITEM';
export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';

export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';


export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_APPOINTMENT_REQUEST = 'GET_APPOINTMENT_REQUEST';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAILURE = 'GET_APPOINTMENT_FAILURE';

export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTS_REQUEST = 'GET_APPOINTMENTS_REQUEST';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAILURE = 'GET_APPOINTMENTS_FAILURE';


export const GET_TICKETLOG = 'GET_TICKETLOG';
export const GET_TICKETLOG_REQUEST = 'GET_TICKETLOG_REQUEST';
export const GET_TICKETLOG_SUCCESS = 'GET_TICKETLOG_SUCCESS';
export const GET_TICKETLOG_FAILURE = 'GET_TICKETLOG_FAILURE';

export const GET_TICKETLOGS = 'GET_TICKETLOGS';
export const GET_TICKETLOGS_REQUEST = 'GET_TICKETLOGS_REQUEST';
export const GET_TICKETLOGS_SUCCESS = 'GET_TICKETLOGS_SUCCESS';
export const GET_TICKETLOGS_FAILURE = 'GET_TICKETLOGS_FAILURE';